name: Deploy to GitHub Pages

on:
  push:
    branches:
      - main

environments:
  deploy:
    url: https://github.com/UnDevelop3d87/Fresno-Resource-Hub

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 16

      - name: Install Node Version Helper Packages
289f5f7b563280838a3a0cae9609f7c0e3e45d7d        uses shortcuts.
